#!/usr/bin/env bash
####################################################
########       Configuração do pw.x         ########
####################################################
PWCOMMAND="/opt/espresso-7.1/bin/pw.x -nk 4"
BANDSCOMMAND="/opt/espresso-7.1/bin/bands.x"
PLOTCOMMAND="/opt/espresso-7.1/bin/plotband.x"
#
###       Grid Set Up                   ###
#$ -N "BD010o1"
#$ -pe physica 64
#$ -cwd
#$ -j y
#
###        Intel MPI Set Up             ###
export OMP_NUM_THREADS=1
export I_MPI_SHM=bdw_avx2
. /opt/intel/oneapi/mkl/latest/env/vars.sh
. /opt/intel/oneapi/mpi/latest/env/vars.sh
MPICOMMAND="/opt/intel/oneapi/mpi/latest/bin/mpiexec -bootstrap ssh"
####################################################
########        Executa as Simulacao        ########
####################################################

${MPICOMMAND} ${PWCOMMAND} -i "scf.in" > "scf.out"

${MPICOMMAND} ${PWCOMMAND} -i "bands.in" > "bands.out"

${BANDSCOMMAND} -i "bands_pp.in" > "bands_pp.out"

 
####################################################
exit 0
